/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hadoop.hdds.scm.simulation;

/**
 * Independent random streams of a simulation, all derived from its seed. Separate streams keep, say, a change in the
 * workload from reshuffling every scheduling decision of an otherwise identical run.
 */
enum SimRandom {
  /** Order in which handlers and due timers run. */
  SCHEDULER,
  /** Client writes. */
  WORKLOAD,
  /** Injected faults. */
  FAULTS,
  /** Datanode delays, report jitter and elections. */
  DATANODE,
  /** Random choices inside SCM, such as placement. */
  SCM,
  /** Pipeline IDs generated by SCM. */
  IDS
}
