name: Ozone Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: 'maven'

      - name: Build all (skip ITs)
        run: mvn -T1C -DskipITs -Dspotbugs.skip -Dpmd.skip -Dcheckstyle.skip -Drat.skip install

      - name: Test server-scm
        run: mvn -pl hadoop-hdds/server-scm -am -DskipITs test

      - name: Archive surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**


