# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: xml-to-md

on:
  push:
    branches:
      - test-branch-2

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    strategy:
      matrix:
        java: [ 8 ]
      fail-fast: false
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache for npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Cache for maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository/*/*/*
            !~/.m2/repository/org/apache/ozone
          key: maven-repo-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-repo-

      - name: Download Ratis repo
        if: ${{ inputs.ratis_args != '' }}
        uses: actions/download-artifact@v4
        with:
          name: ratis-jars
          path: |
            ~/.m2/repository/org/apache/ratis

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Run a full build
        run: hadoop-ozone/dev-support/checks/build.sh -Pdist -Psrc -Dmaven.javadoc.skip=true ${{ inputs.ratis_args }}
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}

      - name: Store binaries for tests
        uses: actions/upload-artifact@v4
        with:
          name: ozone-bin
          path: |
            hadoop-ozone/dist/target/ozone-*.tar.gz
            !hadoop-ozone/dist/target/ozone-*-src.tar.gz
          retention-days: 1

      - name: Store source tarball for compilation
        uses: actions/upload-artifact@v4
        with:
          name: ozone-src
          path: hadoop-ozone/dist/target/ozone-*-src.tar.gz
          retention-days: 1

      - name: Store Maven repo for tests
        uses: actions/upload-artifact@v4
        with:
          name: ozone-repo
          path: |
            ~/.m2/repository/org/apache/ozone
          retention-days: 1

  xml-to-md:
    needs:
      - build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pip unzip

      - name: Download the source tarball
        uses: actions/download-artifact@v4
        with:
          name: ozone-src
          path: .

      - name: Extract the source tarball
        run: |
          mkdir -p ozone-src
          tar -xzf hadoop-ozone/dist/target/ozone-*.tar.gz -C ozone-src

      - name: Run the Python script to convert XML properties into Markdown
        run: python3 dev-support/ci/xml_to_md.py

      - name: Upload the markdown file
        uses: actions/upload-artifact@v4
        with:
          name: Configurations.md
          path: hadoop-hdds/docs/content/tools/Configurations.md

      - name: Download the markdown file
        uses: actions/download-artifact@v4
        with:
          name: Configurations.md

